# Generated by Django 2.2.3 on 2019-09-28 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='isFoodBank',
            new_name='is_food_bank',
        ),
        migrations.AddField(
            model_name='receiverecord',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='contact_person',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expirationrecord',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expirationrecord',
            name='record_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='household',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='household',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='household',
            name='home_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='household',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='household',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='receiverecord',
            name='record_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resource',
            name='expiration_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
