# Generated by Django 2.2.3 on 2019-10-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名稱')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='email')),
                ('pattern', models.CharField(choices=[('Individual', '個人'), ('Agency', '團體'), ('FoodBank', '食物銀行')], default='Individual', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='donationrecord',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='donationrecord',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='expirationrecord',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='location',
            name='agency',
        ),
        migrations.AddField(
            model_name='donationrecord',
            name='contact_person',
            field=models.CharField(blank=True, max_length=30, verbose_name='單位負責人'),
        ),
        migrations.AddField(
            model_name='expirationrecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
        migrations.AddField(
            model_name='donationrecord',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Donator'),
        ),
        migrations.AddField(
            model_name='location',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Donator'),
        ),
    ]
