# Generated by Django 2.2.3 on 2019-10-01 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_day', models.SmallIntegerField()),
                ('prefer_period', models.SmallIntegerField()),
                ('household', models.ForeignKey(on_delete='CASCADE', to='inventory.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('household', models.ForeignKey(on_delete='CASCADE', to='inventory.Household')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Household')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_take', models.DateTimeField()),
                ('time_receive', models.DateTimeField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Household')),
            ],
        ),
        migrations.CreateModel(
            name='User_Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete='CASCADE', to='inventory.Agency')),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='donationrecord',
            old_name='place',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='place',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='expirationrecord',
            name='record_date',
        ),
        migrations.AddField(
            model_name='expirationrecord',
            name='record_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.RenameModel(
            old_name='Place',
            new_name='Location',
        ),
        migrations.DeleteModel(
            name='ReceiveRecord',
        ),
        migrations.AddField(
            model_name='waybill',
            name='location_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_location_export', to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='location_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_location_import', to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementdelivery',
            name='location_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='receiptrecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='freight',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='freight',
            name='waybill',
            field=models.ForeignKey(on_delete='CASCADE', to='inventory.Waybill'),
        ),
        migrations.AddField(
            model_name='content',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='content',
            name='requirement_delivery',
            field=models.ForeignKey(on_delete='CASCADE', to='inventory.RequirementDelivery'),
        ),
    ]
