# Generated by Django 2.2.3 on 2019-10-18 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191018_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatorContacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名稱')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='手機')),
            ],
        ),
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名稱')),
                ('home_number', models.CharField(blank=True, max_length=30, verbose_name='市話')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='地址')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('donation_time', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('record_time', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='receiptrecord',
            name='household',
        ),
        migrations.RemoveField(
            model_name='receiptrecord',
            name='item',
        ),
        migrations.RemoveField(
            model_name='household',
            name='email',
        ),
        migrations.RemoveField(
            model_name='location',
            name='donator',
        ),
        migrations.AddField(
            model_name='donator',
            name='home_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='市話'),
        ),
        migrations.AlterField(
            model_name='donator',
            name='pattern',
            field=models.CharField(choices=[('Individual', '個人'), ('Agency', '團體'), ('FoodBank', '食物銀行')], default='Individual', max_length=10, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='donator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='手機'),
        ),
        migrations.AlterField(
            model_name='expirationrecord',
            name='record_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='household',
            name='home_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='市話'),
        ),
        migrations.AlterField(
            model_name='household',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='手機'),
        ),
        migrations.DeleteModel(
            name='DonationRecord',
        ),
        migrations.DeleteModel(
            name='ReceiptRecord',
        ),
        migrations.AddField(
            model_name='sendrecord',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Household'),
        ),
        migrations.AddField(
            model_name='sendrecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='sendrecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='receiverecord',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Donator'),
        ),
        migrations.AddField(
            model_name='receiverecord',
            name='donator_contacter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.DonatorContacter'),
        ),
        migrations.AddField(
            model_name='receiverecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='receiverecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='donatorcontacter',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Donator'),
        ),
        migrations.AddField(
            model_name='location',
            name='foodBank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.FoodBank'),
        ),
    ]
