# Generated by Django 2.2.3 on 2019-10-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191001_0132'),
        ('inventory', '0002_auto_20190928_0020'),
    ]

    operations = [
    ]
