# Generated by Django 2.2.3 on 2019-10-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191018_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='foodBank',
            new_name='food_bank',
        ),
        migrations.AlterField(
            model_name='donatorcontacter',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Donator', verbose_name='所屬單位'),
        ),
    ]
