# Generated by Django 2.2.3 on 2019-10-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('inventory', '0004_auto_20191018_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonatorContacter',
            new_name='Contacter',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='food_bank',
            new_name='foodbank',
        ),
        migrations.RenameField(
            model_name='receiverecord',
            old_name='donator_contacter',
            new_name='contacter',
        ),
    ]
