# Generated by Django 2.2.4 on 2019-10-27 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20191026_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='expiration_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='有效日期'),
        ),
    ]
