# Generated by Django 2.2.4 on 2019-11-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_receiverecord_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='need_delivery',
        ),
        migrations.AddField(
            model_name='donator',
            name='foodbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.FoodBank', verbose_name='食物銀行'),
        ),
        migrations.AddField(
            model_name='household',
            name='foodbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.FoodBank', verbose_name='食物銀行'),
        ),
        migrations.AlterField(
            model_name='household',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='結束日期'),
        ),
        migrations.AlterField(
            model_name='household',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日期'),
        ),
        migrations.DeleteModel(
            name='ExpirationRecord',
        ),
    ]
