# Generated by Django 2.2.4 on 2019-11-10 22:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20191107_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='population',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='人數'),
        ),
        migrations.AlterField(
            model_name='receiverecord',
            name='donation_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='捐贈日期'),
        ),
        migrations.AlterField(
            model_name='sendrecord',
            name='record_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='領取日期'),
        ),
    ]
