# Generated by Django 2.2.4 on 2019-11-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20191112_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiverecord',
            old_name='donation_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sendrecord',
            old_name='record_time',
            new_name='date',
        ),
    ]
