# Generated by Django 2.2.4 on 2019-11-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191107_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foodbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.FoodBank', verbose_name='食物銀行'),
        ),
    ]
